### PR TITLE
Keep AddCards, EditCurrent, and Browser on top

### PR DESCRIPTION
**Pull request by glutanimate**
With this commit the state for the child windows mentioned above can now also be controlled through the "on-top" toggle.

### CODE REVIEW

**Comment by dae** [comment]
Would you like to take over this add-on? I can assign the AnkiWeb ID to your account so you can update it as you see fit.

**Comment by glutanimate** [comment]
Hey Damien,

this was more of a one-off modification by request from a fellow Anki user. I don't really use the add-on myself, so I don't think I'm the best candidate for maintaining it.

**Comment by dae** [comment]
I merged this and went to update the existing add-on but then realised I was not actually the one sharing it - https://ankiweb.net/shared/info/1830523200 was shared by another user, and I must have removed my shared copy from the listings in the past. The user who shared it verified their email address this year, so you could try posting a review to get their attention, or just upload a separate copy with a disclaimer that you don't want to provide any support.

**Comment by glutanimate** [comment]
Oh, I see! Thanks for letting me know. I'll try to contact the author through a review.

**Pull request merged**
