### PR TITLE
Configure black profile for isort

### PR DESCRIPTION
**Pull request by davidculley**
Use the profile rather than the equivalent custom options.

https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#isort

### CODE REVIEW

**Comment by dae** [comment]
This causes 'make' to fail check_format, as the formatting is no longer the same.

**Comment by davidculley** [comment]
Does it still?

**Comment by dae** [comment]
All good now, thanks.

**Comment by davidculley** [comment]
I'm glad I could help. 🙂

**Pull request merged**
