### PR TITLE
Japanese Support: improve furigana suffix support for reading and bulkreading

### PR DESCRIPTION
**Pull request by dudanian**
I started using more furigana suffix fields and noticed a few problems, namely nothing being generated especially for bulkreadings which apparently had no support.

### CODE REVIEW

**Comment by dae** [comment]
What's your use case for regeneration? I'm not sure it's something most users will need to do, and they can clear out existing fields with find&replace already.

**Comment by dudanian** [comment]
I was doing maintenance on a deck of notes recently with 8 source fields I wanted to add dest fields for. I had manually added readings to some fields, but I decided I wanted to auto-generate all of the readings instead. But when you have readings in the source fields, the generated text doubles the reading like " XXX[YYY][YYY]", so I had to find and fix all the source fields manually and regenerate the readings. Like you mentioned, find/replace could have been an option, but it never even occurred to me. I was honestly debating just deleting and adding the fields again to clear them out.

I mean now that I'm aware I can just regenerate a bunch of fields by find/replace and then bulk-add, I would be fine dropping it. I'm just not sure how much of an obvious solution to the problem that is since clearly it didn't even occur to me.

**Comment by dae** [comment]
Thanks for elaborating. I don't think the demand is there to justify a separate regenerate option at the moment, but if you want to split out the rest of this change I'd be happy to accept the other parts.

**Comment by dudanian** [comment]
Sorry this took me so long. Removed the top commit.

**Comment by dae** [comment]
No problem, cheers

**Pull request merged**
