### PR TITLE
Enhanced user dictionary for mecab.

### PR DESCRIPTION
**Pull request by ianki**
Adds the enhanced user dictionary from cb's Japanese Text Analysis Tool.

### CODE REVIEW

**Comment by ianki** [comment]
Please take a look.  A number of us on Nukemarine's LLJ are using cb's Japanese Text Analysis Tool to create frequency lists for study, combined with MorphMan in Anki.

JTAT by default enables a larger (enhanced) dictionary, which matches significantly more names and compound words than Mecab's system dictionary.  It helps a lot if Anki Support, MorphMan, and JTAT have the same range of dictionary.

Adding this to the Japanese plugin seems like the least hassle way to help folks set things up.

**Comment by dae** [comment]
Would you mind pointing me to the original location of those files, and confirming the license allows their redistribution?

**Comment by ianki** [comment]
The system dictionary is the latest mecab-ipadic.  The user dictionary comes from https://sourceforge.net/projects/japanesetextana/files/ which carries a GPLv3 license.

**Comment by dae** [comment]
I am guessing the user dic is juman, but I can't find anything that confirms it in the source bundle. Could I trouble you to confirm that with cb?

**Comment by ianki** [comment]
I reached out to cb.  It's based on EDICT.

**Comment by dae** [comment]
Thanks for that, I've updated the download.

**Pull request merged**
