### PR TITLE
Update customPlayer.py

### PR DESCRIPTION
**Pull request by SeungHeeHan**
Hello,
May I use KMplayer to play video in Anki?
Have a good day!

### CODE REVIEW

**Comment by dae** [comment]
You can use whichever player you wish by modifying the addon on your machine - there's no need to change the copy available on ankiweb.net.

**Comment by SeungHeeHan** [comment]
I am not a professional technician in IT so just change in order to everyone can check this code for me.

Could you mind showing me a detail way to make the kmplayer as default software when I play video in Anki, please?

How can I make it work on my machine?

Have a good day,

SH






From: Damien Elmes
Sent: ‎Friday‎, ‎11‎ ‎November‎, ‎2016 ‎07‎:‎58
To: dae/ankiplugins
Cc: SeungHeeHan, Author





You can use whichever player you wish by modifying the addon on your machine - there's no need to change the copy available on ankiweb.net.

**Comment by dae** [comment]
I'm sorry, we do not have the resources to provide official support for add-on writing, but you are welcome to ask the community on https://anki.tenderapp.com/discussions/add-ons

**Comment by SeungHeeHan** [comment]
I thought you wrote this code so I asked you for your help. Thanks anyway!

Have a good day!






From: Damien Elmes
Sent: ‎Friday‎, ‎11‎ ‎November‎, ‎2016 ‎10‎:‎16
To: dae/ankiplugins
Cc: SeungHeeHan, Author





I'm sorry, we do not have the resources to provide official support for add-on writing, but you are welcome to ask the community on https://anki.tenderapp.com/discussions/add-ons

**Pull request closed without merging**
